index:
    path: /
    controller: App\Controller\DefaultController::index
detailsmedoc:
    path: /detailsmedoc/{depotlegal}
    controller: App\Controller\DefaultController::detailsmedoc
suppmedoc:
    path: /suppmedoc/{depotlegal}
    controller: App\Controller\DefaultController::suppmedoc
